package com.xiaoyi.manager.dao;

import com.xiaoyi.manager.domain.SendTmpMsgFailed;

public interface ISendTmpMsgFailedDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    int deleteByPrimaryKey(String lessontradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    int insert(SendTmpMsgFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    int insertSelective(SendTmpMsgFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    SendTmpMsgFailed selectByPrimaryKey(String lessontradeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    int updateByPrimaryKeySelective(SendTmpMsgFailed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table send_tmp_msg_failed
     *
     * @mbggenerated Tue Apr 10 09:47:44 CST 2018
     */
    int updateByPrimaryKey(SendTmpMsgFailed record);
}