package com.xiaoyi.manager.dao;

import com.xiaoyi.manager.domain.TeacherPayList;
import com.xiaoyi.manager.domain.TeacherPayListKey;

public interface ITeacherPayListDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    int deleteByPrimaryKey(TeacherPayListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    int insert(TeacherPayList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    int insertSelective(TeacherPayList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    TeacherPayList selectByPrimaryKey(TeacherPayListKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    int updateByPrimaryKeySelective(TeacherPayList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_pay_list
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    int updateByPrimaryKey(TeacherPayList record);
}