package com.xiaoyi.manager.domain;

public class TeacherPayList extends TeacherPayListKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_pay_list.feedback
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    private String feedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher_pay_list.reward
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    private Float reward;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_pay_list.feedback
     *
     * @return the value of teacher_pay_list.feedback
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    public String getFeedback() {
        return feedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_pay_list.feedback
     *
     * @param feedback the value for teacher_pay_list.feedback
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    public void setFeedback(String feedback) {
        this.feedback = feedback == null ? null : feedback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher_pay_list.reward
     *
     * @return the value of teacher_pay_list.reward
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    public Float getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher_pay_list.reward
     *
     * @param reward the value for teacher_pay_list.reward
     *
     * @mbggenerated Mon Mar 12 11:32:25 CST 2018
     */
    public void setReward(Float reward) {
        this.reward = reward;
    }
}